"""Add low_balance_alert_sent

Revision ID: 4982c5c7b7c8
Revises: 
Create Date: 2026-03-24 23:46:11.944801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4982c5c7b7c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'run_command',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('low_balance_alert_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'low_balance_alert_sent')
    op.alter_column('jobs', 'run_command',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
